# -*- coding: utf-8 -*-
"""assignment2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EME-NVGr41e8YmFrk_jthBOPwBUtyBPL
"""



"""#Write a Python program to print all positive numbers in a range.


"""

li = [12, -7, 5, 64, -14] 
for i in li:   
    if i >= 0:
       print(i)

"""#this is the second problem in the assignment"""

li = [12, 14, -95, 3]
for i in li:
  if i >= 0:
    print(i)

