# -*- coding: utf-8 -*-
"""assignment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P9tjMInDmjYVLHCahRLXdG4n46U2Z3w-
"""



"""#this is the first assignment given in the app

#Python program which accepts the radius of a circle from the user and computes area.
"""

x =float(input("radius of the circle is :"))
print(3.1415*x**2)



"""#Python program to accept a filename from the user and print the extension of that."""

x = input("Enter Filename: ")
x = x.split(".")

print ("Extension of the file is : " + x[-1])

